blank_issues_enabled: false

contact_links:
  - name:  "Issue with website"
    about: "Please open issues relating to the website in 'OctalMesh/OctalWeb'"
    url:   "https://github.com/OctalMesh/OctalWeb/issues/new/choose"

  - name:  "Issue with design"
    about: "Please open issues relating to design in 'OctalMesh/OctalDesign'"
    url:   "https://github.com/OctalMesh/OctalDesign/issues/new/choose"

  - name:  "Issue with font"
    about: "Please open issues relating to font in 'OctalMesh/OctalFont'"
    url:   "https://github.com/OctalMesh/OctalFont/issues/new/choose"

  - name:  "🌐 Website"
    about: "Check out our official website"
    url:   "https://octalmesh.com/"

  - name:  "📣 Socials"
    about: "Join us on social media platforms"
    url:   "https://socials.octalmesh.com/"
